### ISSUE TITLE
Exception in train

### ISSUE THREAD

**Issue by RXin-he** [zhaojw1998/Beat-Transformer#14]
When training, errors will be reported in the loss function. When I run on the cpu, the specific error message is as follows:
Traceback (most recent call last):
  File "code/train.py", line 367, in <module>
       _, _, _, _, _, _ = train(model, train_loader, optimizer, scheduler, loss_func, loss_tempo, CLIP, epoch, DEVICE)
  File "code/train.py", line 177, in train
       loss_t = loss_tempo(torch.softmax(tempo, dim=-1), valid_tempo_gt)
RuntimeError: all elements of input should be between 0 and 1

**Comment by zhaojw1998** [comment]
> When training, errors will be reported in the loss function. When I run on the cpu, the specific error message is as follows: Traceback (most recent call last): File "code/train.py", line 367, in _, _, _, _, _, _ = train(model, train_loader, optimizer, scheduler, loss_func, loss_tempo, CLIP, epoch, DEVICE) File "code/train.py", line 177, in train loss_t = loss_tempo(torch.softmax(tempo, dim=-1), valid_tempo_gt) RuntimeError: all elements of input should be between 0 and 1

That is strange, since it works on my end. But anyway, I think the error means either the prediction term (i.e., "torch.softmax(tempo, dim=-1)") or the ground-truth term ("valid_tempo_gt") has values out of the [0, 1] range. It is more likely the latter case.  Adding the following to line 177 should work:
valid_tempo_gt[tempo_gt <0] = 0
valid_tempo_gt[tempo_gt >1] = 1

**Comment by RXin-he** [comment]
Sorry to reply you so late, your answer is very useful. However, I used “loss_tempo = nn.BCEWithLogitsLoss(reduction='none')” instead of “loss_tempo = nn.BCELoss(reduction='none')” and removed the softmax, and the model trained.

**Comment by RXin-he** [comment]
> > When training, errors will be reported in the loss function. When I run on the cpu, the specific error message is as follows: Traceback (most recent call last): File "code/train.py", line 367, in _, _, _, _, _, _ = train(model, train_loader, optimizer, scheduler, loss_func, loss_tempo, CLIP, epoch, DEVICE) File "code/train.py", line 177, in train loss_t = loss_tempo(torch.softmax(tempo, dim=-1), valid_tempo_gt) RuntimeError: all elements of input should be between 0 and 1
> 
> That is strange, since it works on my end. But anyway, I think the error means either the prediction term (i.e., "torch.softmax(tempo, dim=-1)") or the ground-truth term ("valid_tempo_gt") has values out of the [0, 1] range. It is more likely the latter case. Adding the following to line 177 should work: valid_tempo_gt[tempo_gt <0] = 0 valid_tempo_gt[tempo_gt >1] = 1

Sorry to reply you so late, your answer is very useful. However, I used “loss_tempo = nn.BCEWithLogitsLoss(reduction='none')” instead of “loss_tempo = nn.BCELoss(reduction='none')” and removed the softmax, and the model trained.
